services:
  node:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api/index.js:/src/index.js
  backend:
    build:
      context: ./server
    volumes:
      - ./server/server.js:/server.js
    ports:
      - 3000:3000
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8089:80
    volumes:
      - ./static/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
      - backend
